### PR TITLE
feat(animated-items): pass animatedValue into renderItem

### PR DESCRIPTION
**Pull request by alfonsosn**
### Platforms affected

Android and iOS. Only affects the UI Thread.

### What does this PR do?

Passes the `animatedValue` inside the `renderItem` function. Items can access the values to animate other elements inside the Item.

### What testing has been done on this change?

QA

### Tested features checklist

- [x] Default setup ([example](https://github.com/archriss/react-native-snap-carousel/blob/master/example/src/index.js#L46-L87))
- [ ] Carousels with and without momentum enabled ([prop `enableMomentum`](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#behavior))
- [ ] Vertical carousels ([prop `vertical`](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#behavior))
- [x] Slide alignment ([prop `activeSlideAlignment`](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#style-and-animation))
- [x] Autoplay ([prop `autoplay`](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#autoplay))
- [x] Loop mode ([prop `loop`](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#loop))
- [x] `ScrollView`/`FlatList` carousels ([prop `useScrollView`](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#behavior))
- [x] [Callback methods](https://github.com/archriss/react-native-snap-carousel/blob/master/doc/PROPS_METHODS_AND_GETTERS.md#callbacks)
- [x] [`ParallaxImage` component](https://github.com/archriss/react-native-snap-carousel#parallaximage-component)
- [x] [`Pagination` component](https://github.com/archriss/react-native-snap-carousel#pagination-component)
- [ ] [Layouts and custom interpolations](https://github.com/archriss/react-native-snap-carousel#layouts-and-custom-interpolations)

### CODE REVIEW

**Comment by maherzaidoune** [comment]
I've created a pull request with that change and it's not merged yet,  #709 ,
anyway, I've added support to change useNativeDriver so developer could make animation not supported by native drivers like the background color.

**Comment by ajacquierbret** [comment]
@bd-arc It'd be awesome to check and merge this one ! :)
Talking about #745 but also about #709 (or maybe both if they are complementary)

Also, I'm currently facing an issue concerning Animated API animations made inside rendered items of the carousel. Animations simply don't work, precisely color interpolations. I don't use native driver since I rely on `backgroundColor` animated values, so the "natural" behaviour of this library (`useNativeDriver = true`) may be interfering with mine ?

Is there a chance that these PRs will make animations inside renderItem component working ? Or am I simply doing something wrong ?

**Comment by maherzaidoune** [comment]
> #709

in #709 I mentioned an example for color interpolations inside renderItem 
here is a link to the sample I created for the PR 
https://github.com/maherzaidoune/Custom-animated-item-demo

**Comment by ajacquierbret** [comment]
@maherzaidoune What I meant is that an independant animation based on React Animated API isn't working at all inside rendered items of the carousel. I don't even need to pass animated values to renderItem, since my animation doesn't rely on the swiper and are totally independant of any scroll behaviour, and it'd be totally usable without any swiper component.
I was questioning about the fact that animations aren't working with components rendered by react-native-snap-carousel but are perfectly working with components rendered by react-native-swiper library. So I thought that Flatlist was the culprit but even with the `useScrollView` prop, animations don't fire.

@bd-arc Any ideas on what could cause this issue ?

**Comment by ajacquierbret** [comment]
I filled out an issue template to adress this problem : #756

**Pull request closed without merging**
